Attempted to make the cleanup async, although depends on using bash

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -48,13 +48,15 @@ jobs:
           when: always
           command: |
             set +x
+            num_failures=0
+            pids=( )
+
             function az_login {
                 az login --service-principal -u http://CircleCI -p $TF_VAR_azure_client_secret --tenant $TF_VAR_azure_tenant_id > /dev/null
             }
 
             function gcp_login {
                 gcloud auth activate-service-account --key-file=<(echo $TF_VAR_google_creds_base64 | base64 -d) --project=$TF_VAR_google_project_id 
-                gcloud iam service-accounts list
             }
 
             function clean_gcp {
@@ -63,7 +65,7 @@ jobs:
                 do
                     name=$(echo $c | cut -f 1 -d,)
                     zone=$(echo $c | cut -f 2 -d,)
-                    gcloud container clusters delete -q $name --zone $zone
+                    gcloud container clusters delete -q $name --zone $zone & pids+=( $! )
                 done
             }
 
@@ -71,7 +73,7 @@ jobs:
                 groups=$(az group list --query "[?tags.hydra_project=='$TF_VAR_project_name' && properties.provisioningState != 'Deleting'].name" -o tsv)
                 for g in $groups
                 do
-                    az group delete -y --name $g
+                    az group delete -y --name $g & pids+=( $! )
                 done
             }
 
@@ -79,7 +81,7 @@ jobs:
                 app_ids=$(az ad app list --all --query "[?contains(displayName,'$TF_VAR_project_name')].appId" -o tsv)
                 for app_id in $app_ids
                 do
-                    az ad app delete --id $app_id
+                    az ad app delete --id $app_id & pids+=( $! )
                 done
             }
 
@@ -103,8 +105,19 @@ jobs:
                 users=$(gcloud iam service-accounts list --filter="displayName='Registry User'" --format="value(email)")
                 for u in $users
                 do
-                  gcloud iam service-accounts delete -q --project $TF_VAR_google_project_id $u
+                  gcloud iam service-accounts delete -q --project $TF_VAR_google_project_id $u & pids+=( $! )
                 done
+            }
+
+            function wait_for_processing {
+              for pid in "${pids[@]}"; do
+                wait "$pid" || (( ++num_failures ))
+              done
+
+              if (( num_failures > 0 )); then
+                echo "Warning: $num_failures background processes (out of ${#pids[@]} total) failed" >&2
+              fi
+              pids=( )
             }
             #clean_akamai
 
@@ -112,8 +125,11 @@ jobs:
             az_login
             clean_azure
             clean_gcp
+            wait_for_processing
             clean_az_creds
             clean_gcp_creds
+            wait_for_processing
+            exit num_failures
 
 workflows:
   version: 2
